[package]
edition = "2021"
name = "bevy_atari_antic"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {path = "../../bevy", default_features = false, features = ["bevy_core_pipeline", "bevy_render2", "bevy_sprite2", "bevy_winit", "x11", "trace_chrome"]}
bytemuck = {version="1.7", features=["derive"]}
crevice = {path = "../../bevy/crates/crevice/"}
wgpu = { version = "0.11", features = ["spirv", "webgl"] }
parking_lot = "0.11"
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Storage"]}
futures-lite = "1.11.3"

[[example]]
name = "atari_antic"
path = "examples/atari_antic.rs"

[profile.release]
# opt-level = "z"
# lto = true
# codegen-units = 1

[patch.crates-io]
wgpu = {git="https://github.com/gfx-rs/wgpu", revision="c824c8"}
glow = {git="https://github.com/mrk-its/glow", branch="read_pixels_array_buffer_view"}